#!/opt/anaconda3/bin/python3

import numpy
import pandas
import scipy.stats as stats
import sys

if __name__ == "__main__":
    inventory_file = sys.argv[1]
    sales_file = sys.argv[2]
    operator_id = int(sys.argv[3])
    
    inventory_data = pandas.read_csv(inventory_file, parse_dates=[0], infer_datetime_format = True)
    sales_data = pandas.read_csv(sales_file, parse_dates=[0], infer_datetime_format = True)

    filtered_inventory_data = inventory_data[inventory_data.operator_id == operator_id]
    filtered_sales_data = sales_data[sales_data.operator_id == operator_id]

    