#!/bin/bash

#
#   TODO: Use a decent build system.
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PYTHON3="/opt/anaconda3/bin/python3"
$PYTHON3 "$SCRIPT_DIR/lib/native/setup.py" build_ext