#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SOLUTION_DIR="$(cd "${SCRIPT_DIR}/../../../" && pwd)" 
DATA_INPUT_DIR="${SOLUTION_DIR}/data/input"
DATA_OUTPUT_DIR="${SOLUTION_DIR}/data/output"
PYTHON="/opt/anaconda3/bin/python3"
PYTHONPATH="${SOLUTION_DIR}/lib"
PYTHONMATH='CPU'
export PYTHONPATH


$PYTHON "${SCRIPT_DIR}/randomized-block.py" $1